# Generated by Django 4.0.2 on 2022-03-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate', '0002_artwork_lat_artwork_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='cluster_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='color_0',
            field=models.CharField(default='[0, 0, 0, 0]', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='color_1',
            field=models.CharField(default='[0, 0, 0, 0]', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='color_2',
            field=models.CharField(default='[0, 0, 0, 0]', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='color_3',
            field=models.CharField(default='[0, 0, 0, 0]', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='color_4',
            field=models.CharField(default='[0, 0, 0, 0]', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='color_5',
            field=models.CharField(default='[0, 0, 0, 0]', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='descriptions',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='keywords',
            field=models.CharField(default='[]', max_length=200),
            preserve_default=False,
        ),
    ]
