# Generated by Django 4.0.2 on 2022-04-17 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulate', '0003_artwork_cluster_id_artwork_color_0_artwork_color_1_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artwork',
            table='artwork',
        ),
    ]
