# Generated by Django 4.0.2 on 2022-04-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulate', '0005_interactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactions',
            name='liked',
        ),
        migrations.AddField(
            model_name='interactions',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
